url: https://github.com/okuspocus
baseurl: /okuspocus.github.io

# Site settings
title: MBP Serveis
email: your-email@domain.com
description: "Reformas, Pintura, Renovacio i Reparacions, Fontaneria, Instalacions, Exteriors, Interiorisme, Acondicionament Jardins, Ca n'Amat, Projectes"


# Team names, titles and social links
people:
- name: Moisès Bartual Pont
  pic: 1
  position: 
  social:
    - title: instagram
      url: #
    - title: whatsapp
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Ca n'Amat Paradis
  - line: 08635 Sant Esteve Sesrovires

# Build settings
markdown: kramdown
permalink: pretty
